#ifndef PROJ_SRC_DATA_LINK_LAYER_INCLUDE_ERROR_NOS_H_
#define PROJ_SRC_DATA_LINK_LAYER_INCLUDE_ERROR_NOS_H_

#define SUCCESS 0
#define NULL_POINTER_ERROR (-1)
#define EOF_DISCONNECT (-2)
#define TOO_MANY_ATTEMPTS (-3)
#define TIMED_OUT (-4)
#define IO_ERROR (-5)
#define INVALID_RESPONSE (-6)
#define BUFFER_OVERFLOW (-7)
#define OUT_OF_ORDER (-8)
#define PARITY_ERROR_1 (-9)
#define PARITY_ERROR_2 (-10)
#define CONFIGURATION_ERROR (-11)
#define WRONG_HEADER (-12)

#endif  // PROJ_SRC_DATA_LINK_LAYER_INCLUDE_ERROR_NOS_H_
